package br.com.kuntzedevprojects.money_master_2.enums;

public enum FinanceCommandType {
    REGISTER_TRANSACTION,
    CHANGE_TRANSACTION_CATEGORY_BY_CATEGORY,
    CHANGE_TRANSACTION_CATEGORY_BY_DESCRIPTION_DATE,
    CREATE_CATEGORY,
    DEPOSIT_SAVINGS_JAR,
    WITHDRAW_SAVINGS_JAR,
    REGISTER_SAVINGS_JAR_YIELD,
    RECONCILE_SAVINGS_JAR_YIELD,
    RECONCILE_SAVINGS_JAR_BALANCE
}
