package br.com.kuntzedevprojects.money_master_2.enums;

public enum FinanceCommandType {
    REGISTER_TRANSACTION,
    CHANGE_TRANSACTION_CATEGORY_BY_CATEGORY,
    CHANGE_TRANSACTION_CATEGORY_BY_DESCRIPTION_DATE,
    CREATE_CATEGORY,
    DEPOSIT_SAVINGS_JAR,
    WITHDRAW_SAVINGS_JAR,
    REGISTER_SAVINGS_JAR_YIELD,
    RECONCILE_SAVINGS_JAR_YIELD,
    RECONCILE_SAVINGS_JAR_BALANCE,
    CREATE_MONTHLY_PLAN_ITEM,
    PAY_MONTHLY_PLAN_ITEM,
    REOPEN_MONTHLY_PLAN_ITEM,
    INCREASE_MONTHLY_PLAN_ITEM_EXPECTED_AMOUNT,
    CREATE_INSTALLMENT_MONTHLY_PLAN_ITEMS,
    LINK_TRANSACTION_TO_MONTHLY_PLAN_ITEM,
    RECONCILE_MONTHLY_PLAN_WITH_TRANSACTIONS
}
